CREATE DATABASE politicos;

USE politicos;

CREATE TABLE politico(
	id 			 	INT NOT NULL AUTO_INCREMENT,
    nome 		 	VARCHAR (100) 	NOT NULL,
    partido 	 	VARCHAR (45) 	NOT NULL,
    descricao	 	TEXT NULL,
	dtnascimento 	DATE NULL,
    email		 	VARCHAR (80) NULL,
    perfilfacebook	VARCHAR (80) NULL,
    PRIMARY KEY(id)
);

INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES	('Dr. Alexandre Dentista','PSDC','Alexandre Rodrigues de Oliveira foi reeleito em 2016 com 3.444 votos. Natural de Uberlândia (MG) mudou-se para Guarulhos em 1969. É dentista e mora na Vila Galvão.','1962-11-5','dr.alexandredentista@camaraguarulhos.sp.gov.br','https://www.facebook.com/dr.alexandredentistaguarulhos');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Dr. Laércio Sandes','DEM','Laércio Sandes de Oliveira foi reeleito com 4.544 votos, um crescimento de 55% considerando sua primeira eleição em 2012, quando obteve 2.930 votos. Natural de Goioerê (PR), mudou-se em 1980 para Guarulhos. Viveu sua adolescência e juventude no Taboão e atualmente reside na região central da cidade. Foi filiado ao PMN por 22 anos, mas em 2016 migrou para o DEM motivado pelo desejo de lutar ainda mais pelo melhor para o município. ','1970-3-8','drlaercio@camaraguarulhos.sp.gov.br','https://www.facebook.com/laerciosandes?fref=ts');                                                                   ;
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Edmilson Lula Souza','PT','Edmilson Souza Santos foi reeleito para seu terceiro mandato em 2016 com 3.954 votos. Natural de São Paulo (SP), mudou-se para Guarulhos com apenas 2 meses de idade. Filiado ao PT desde os 14 anos, foi secretário de Cultura do município entre 2001 e 2008. Ocupou a Vice-Presidência da Câmara no biênio 2011-2012.','1972-4-28','edmilsonsouza@camaraguarulhos.sp.gov.br',null);
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Eduardo Barreto','PCdoB','Carlos Eduardo Barreto foi reeleito em 2016 com 5.879 votos. Natural de Irecê (BA), mora no Jardim Fortaleza. Servidor público estadual, já trabalhou como estoquista e policial militar. É filiado ao PCdoB desde o início de 2012.','1981-3-28','eduardobarreto@camaraguarulhos.sp.gov.br',' https://www.facebook.com/pages/Eduardo-Barreto/465153386878346');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Eduardo Soltur','PSB','Eduardo Antônio da Silva Pires foi reeleito em 2016 para seu quinto mandato com 5.099  votos. Natural de São Paulo (SP), foi deputado estadual (1999-2002) e presidente da Câmara de Guarulhos nos biênio 2011-2012, 2013-2014. Na primeira sessão de 2017, foi novamente eleito para presidir a Câmara, cargo que ocupou pela terceira vez no biênio 2017-2018.','1961-8-3','eduardosoltur@camaraguarulhos.sp.gov.br','https://www.facebook.com/pages/Eduardo-Soltur/122252124585586');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Genilda Lula Bernardes','PT','Genilda Sueli Bernardes foi reeleita em 2016 com 4.420 votos. Filiou-se ao PT em 1991, ainda em Presidente Prudente (SP), onde começou sua vida política. Lá foi suplente de vereador, membro do sindicato dos servidores municipais e dirigente da Central Única dos Trabalhadores. Mudou-se para Guarulhos em 2001, na condição de servidora pública na área da Educação. Em 2008, dirigiu o Fundo Social da cidade, onde coordenou, entre outros, o programa Bolsa Família.','1962-4-10','genilda@camaraguarulhos.sp.gov.br',null);
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Geraldo Celestino','PSDB','Geraldo Alves Celestino Filho é o primeiro suplente do PSDB, atualmente em exercício devido à licença do vereador Gilvan Passos. Natural de Mandaguaçu (PR), mora no Parque Cecap. Foi suplente de vereador pelo PT em 1990 e eleito titular em 1992, 1996, 2004 e 2008. É filiado ao PSDB desde 2003. Herdou do pai o gosto pelo sindicalismo, causas sociais e política. “Naquele ambiente percebi as possibilidades de mudar a vida das pessoas para melhor”, afirma.','1958-6-1','www.geraldocelestino.com.br','www.facebook.com/celestinogeraldo');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Gilvan Passos','PSDB','Gilvan Passos Leite foi reeleito em 2016 com 4.784 votos. Está atualmente licenciado da vereança para ocupar o cargo de secretário de Segurança Pública de Guarulhos. Natural de São Paulo (SP), mudou-se para Guarulhos em 1969. É servidor público estadual e mora no bairro Torres Tibagy. Bacharel em Direito, atua na política desde 1984, tendo se filiado ao MDB e posteriormente ao PSDB. ','1968-1-4','gilvanpassos@camaraguarulhos.sp.gov.br','https://www.facebook.com/vereadorgilvanpassos?fref=ts ');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('João Barbosa','PRB','João Barbosa de Carvalho foi reeleito em 2016 com 7.074  votos. Nascido em Flórida Paulista (SP), cresceu e foi criado em Franco da Rocha (SP), onde começou a trabalhar na indústria metalúrgica e a frequentar a igreja evangélica. Anos mais tarde, como pastor, mudou-se para Guarulhos. Já foi candidato a deputado estadual em 2002 e em 2006.','1957-06-24','joaobarbosa@camaraguarulhos.sp.gov.br','https://www.facebook.com/joaobarbosa10123');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('João Dárcio','PODEMOS','João Dárcio Ribamar Sacchi, foi Presidente Estadual do PTN em São Paulo e hoje é Presidente do PODEMOS na cidade. Foi reeleito para seu terceiro mandato com 4.298 votos. Suplente em três outras legislaturas e titular entre 2001 e 2004, ele se filiou em 1998 ao PTN - partido que em 2017 passou a se chamar PODEMOS. Nascido em Guarulhos, é filho de João Dárcio e neto de José Ribamar Matos Silva, que também foram vereadores do município. Bacharel em Análises de Sistemas e em Direito, é advogado e Oficial do Exército da Reserva no posto de 1º Tenente. Foi secretário de Segurança Pública da cidade de 2009 a 2012.','1970-12-18','joaodarcio@camaraguarulhos.sp.gov.br',null);
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Lame','MDB','Lameh Abdul Rahman Smeili foi reeleito para o terceiro mandato com 3.996 votos. Natural do Líbano, foi revisor e repórter da Folha de S. Paulo e dos extintos Jornal da Tarde e Diário Popular. Mora no Parque Continental I. Formado em Comunicação Social, tem como uma de suas principais bandeiras a luta pelos direitos dos idosos. ','1963-1-2','lame@camaraguarulhos.sp.gov.br','https://www.facebook.com/lame.vereador?fref=ts');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Marcelo Seminaldo','PT','Marcelo Nunes Seminaldo foi reeleito em 2016 com 5.293 votos. Natural de Guarulhos, é advogado e mora na Vila Galvão. É filiado ao PT desde 1992. Ele conta que seu pai foi um dos fundadores do partido em Guarulhos, juntamente com o ex-prefeito Elói Pietá. A gráfica do PT ficava em sua casa.','1978-3-3','marceloseminaldo@camaraguarulhos.sp.gov.br','https://www.facebook.com/marcelo.seminaldo?fref=ts');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Professor Jesus','DEM','Jesus Roque de Freitas foi reeleito em 2016 com 5.828  votos pelo DEM, após ter ocupado a presidência da Câmara no biênio 2015-2016. No final de 2018, foi eleito novamente presidente da Câmara, cargo que ocupará no biênio 2019-2020. Natural de Cardoso (SP), mora em Guarulhos no Jardim Maria Dirce. Bacharel em Letras pela Faculdade de Guarulhos, é professor universitário na mesma instituição, onde leciona Português. Em 2008, foi eleito suplente de vereador.',null,' jesus@camaraguarulhos.sp.gov.br','http://www.facebook.com/pages/Vereador-Prof-Jesus/237900293017926');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Prof. Rômulo Lula','PT','Rômulo Ornelas de Oliveira foi reeleito para seu segundo mandato com 6.204 votos. Natural de Comercinho (MG), mora em Guarulhos no bairro dos Pimentas. Professor de Ensino Médio, é filiado ao PT desde 1984.Idealizador e fundador do Cursinho Comunitário Pimentas, projeto social que já possibilitou o ingresso de centenas de estudantes nas melhores universidades do país, o vereador realiza ainda uma série de outros trabalhos sociais na periferia da cidade.','1960-7-30','romulo@camaraguarulhos.sp.gov.br','http://www.facebook.com/Romuloornelas');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Ramos da Padaria','DEM','Severino Bezerra de Andrade foi reeleito com 4.136 votos. Natural de Sairé (PE), veio para São Paulo em busca de novas oportunidades, tendo como seu maior investimento uma padaria no bairro dos Pimentas, em Guarulhos.','1966-12-30','ramosdapadaria@camaraguarulhos.sp.gov.br','https://www.facebook.com/ramos.dapadaria?fref=ts');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Romildo Santos','DEM','Romildo Virginio dos Santos foi eleito para seu terceiro mandato como o vereador mais votado do município, com 7.681  votos. Filho de imigrantes nordestinos, nasceu em São Paulo (SP) e mudou-se para Guarulhos aos 7 anos.  Atualmente mora no Parque Mikail. É comerciário e filiou-se ao PSDB em 2007. Em 2016, migrou para o DEM.','1969-3-14','romildosantos@camaraguarulhos.sp.gov.br','https://www.facebook.com/45romildosantos?fref=ts');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Toninho da Farmácia','PSD','Antônio Roberto da Silva foi reeleito com 2.487 votos. Natural de Contagem, região metropolitana de Belo Horizonte (MG), mudou-se para Guarulhos aos 6 anos e mora no bairro de Cumbica. Administra a própria drogaria','1965-5-3','toninhodafarmacia@camaraguarulhos.sp.gov.br','https://www.facebook.com/ToninhodaFarmaciaVereador?fref=ts');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Maurício Lula Brinquinho','PT','Nascido e criado em Guarulhos, Maurício Brinquinho participou da vida política da cidade desde sua juventude, nos movimentos estudantis do SENAI e no movimento dos caras-pintadas.Morador do Jardim Paraventi durante grande parte de sua vida, vivenciou de perto diversos problemas da região, como a falta de ruas asfaltadas, escolas, água e luz.Após se tornar motorista de ônibus, ingressou na luta sindical e passou a lutar pelos direitos dos trabalhadores. Foi eleito presidente do Sindicato dos Condutores de Guarulhos e, em uma luta conjunta com a categoria, conquistou aumentos salariais e benefícios significativos aos condutores, como cesta básica gratuita, participação nos lucros e resultados igual para todos, o fim da dupla função nas linhas municipais, manutenção do vale-refeição durante as férias, entre outros.',null,'mauricio.brinquinho@camaraguarulhos.sp.gov.br','fb.com/mauriciobrinquinho');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Serjão Inovação','PSL','Sergio Luiz da Silva, mais conhecido como Serjão Inovação, foi eleito com 4516 votos. Filiou-se ao PSL em 2010. Em 2016 concorreu às eleições pela segunda vez.Nasceu em 1974 no estado de Pernambuco, é operador de máquinas, casod e pai de três filhos. Mora em Guarulhos desde a década de 70. Atualmente reside na região do Taboão.','1974-01-14','serjao.inovacao@camaraguarulhos.sp.gov.br',null);
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Lauri Rocha','PSDB','Lauri Afonso de Oliveira Rocha é empresário do setor de terraplanagem e chega à Câmara de Guarulhos para seu primeiro mandato de vereador (2017-2020) com 3.184 votos obtidos no dia 2 de outubro pelo PSDB. Lauri Rocha, nome parlamentar escolhido por ele, nasceu na cidade de Lins, interior de São Paulo, mas vive em Guarulhos desde 1967, atualmente no bairro da Ponte Grande.',null,'lauri.rocha@camaraguarulhos.sp.gov.br',null);
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Acácio Portella','PP','Acácio Portella foi eleito para seu primeiro mandato com 2380 votos pelo PP. Guarulhense, ele reside no bairro Vila Endres. É comerciante da região onde possui uma lanchonete há 23 anos. Já passou por outros três partidos (PV, PTN e PMN). Ele foi 2º suplente nas eleições de 2008 e de 2012, mas nas ocasiões não chegou a assumir a vereança.','1969-07-10','acacioportella@camaraguarulhos.sp.gov.br','https://www.facebook.com/portellacomguarulhos/');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Wesley Casa Forte','PSB','Com 2.872 votos, o guarulhense Wesley Casa Forte (PSB), chega à Câmara de Guarulhos como vereador eleito pela primeira vez. Há quatro anos, Wesley ficou na suplência de seu partido e chegou a assumir a vaga por apenas 15 dias durante o mandato que se encerra em 31 de dezembro deste ano.Nascido Wesley Alberto Marino no dia da padroeira de Guarulhos, Nossa Senhora da Conceição, em 8 de dezembro de 1979, Wesley é noivo de Simone e pai de Bruno, de 10 anos. Segundo ele, desde criança sonhava em se tornar político e atuar para melhorar a situação da população menos favorecida.',null,null,'wesleycasaforte@camaraguarulhos.sp.gov.br');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Janete Lula Pietá','PT','Janete é fundadora do Partido dos Trabalhadores (PT) e exerceu dois mandatos como deputada federal, de 2007 a 2015. Mora no bairro Gopoúva, em Guarulhos. É casada e tem três filhos. Formada em história e arquitetura, já trabalhou como professora e atuou na área gráfica e no setor metalúrgico.',null,null,'janete.pieta@camaraguarulhos.sp.gov.br');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Moreira','PTB','José de Vasconcelos Pereira, mais conhecido como Moreira, foi eleito com 1966 votos. Filiou-se ao PTB em 2014. Em 2016 concorreu às eleições pela quarta vez.Nasceu em 1962 no estado da Paraíba, é comerciante, casado e pai de dois filhos. Mora em Guarulhos desde 1977. Atualmente reside no bairro Vila Paraíso.Desenvolve trabalhos sociais na área da saúde e pretende ampliar suas atividades nesta área enquanto vereador. Também pretende apoiar as ações do Prefeito naquilo que julgar ser importante para a população.','1962-06-12','www.facebook.com/ptbvereadormoreira','moreira@camaraguarulhos.sp.gov.br');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Sandra Gileno','PSL','Sandra Regina Major, mais conhecida como Sandra Gileno, foi eleita com 3.453 votos. Filiou-se ao PSL em 2010. Em 2016 concorreu às eleições pela primeira vez.Nasceu em 1972 no estado do Paraná, é comerciante, casada e mãe de dois filhos. Mora em Guarulhos desde 1980. Atualmente mora na região central da cidade.Casada com o deputado estadual Gileno (PSL), a vereadora pretende continuar desenvolvendo os trabalhos já iniciados pelo marido, que também ocupou uma das cadeiras do Legislativo guarulhense durante a legislatura 2013-2016.','1972-02-04',null,'sandra.gileno@camaraguarulhos.sp.gov.br');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Pastor Anistaldo','PSC','Anistaldo Luiz Lopes da Silva foi reeleito em 2016 com 5.279 votos. Natural de Santa Luzia do Norte (AL) mora no bairro São Miguel Pimentas. Bacharel em Teologia e Gestão Pública é funcionário público há 12 anos e pastor evangélico há 15, tendo encabeçado projetos sociais destinados aos menos favorecidos. Foi cobrador de ônibus e ajudante geral','1969-3-8','anistaldo@camaraguarulhos.sp.gov.br','https://www.facebook.com/VereadorPastorAnistaldo?fref=ts');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Zé Luiz Lula','PT','José Luiz Ferreira Guimarães foi reeleito para seu terceiro mandato com 4.632 votos. Natural de Guarulhos, é filiado ao partido desde 1982, época em que era militante sindical pela categoria bancária. Vive no Jardim Rosa de França.','1960-1-11','zeluizpt@camaraguarulhos.sp.gov.br',null);
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Betinho Acredite','PTB','Alberto Saturnino da Silva foi eleito para seu primeiro mandato com 1.968 votos. Filiou-se ao PTB há dois anos. É a primeira vez que concorre às eleições. Nasceu em Guarulhos (SP), no bairro dos Pimentas. É casado e tem uma filha. Mora no Jardim Leblon.Professor de educação física licenciado da rede estadual de ensino lecionou nas escolas estaduais Pastor João Nunes, Bartholomeu de Carlos e Professor Licinio Carpinelli. Já trabalhou de vendedor de limão em frente ao prédio da Câmara.','1974-01-22','betinho.acredite@camaraguarulhos.sp.gov.br',null);
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Thiago Surfista','PRTB','Thiago Surfista, filiado ao PRTB, foi eleito com 3352 votos.  O vereador foi candidato por duas vezes (em 2012 e 2016) e já passou pelo partido PCdoB. Nascido na cidade de São Paulo, o parlamentar mudou-se para Guarulhos quando tinha apenas três anos de idade e, atualmente, reside no Parque Cecap. É funcionário público federal e está licenciado para praticar a vereança.','1982-07-22',null,'thiago.surfista@camaraguarulhos.sp.gov.br');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Eduardo Carneiro','PSB','Eduardo Carneiro foi eleito para seu segundo mandato com 2.407 votos. Foi vereador pela primeira vez em 2009. Exerce atualmente as funções de líder do Governo na Câmara e de 1º vice-presidente da Mesa Diretora.Natural de Campo Belo (MG), mudou-se para Guarulhos há aproximadamente 30 anos. É casado e tem dois filhos: uma dermatologista e um cardiologista. Mora no Jardim Maia.','1960-06-06',null,'dr.eduardocarneiro@camaraguarulhos.sp.gov.br');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Jorge Tadeu','MDB',null,null,null,null);
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Paulo Roberto Cecchinato','PP','Paulo Roberto Cechinatto chega à Câmara para cumprir seu nono mandato como vereador. Eleito pelo PP com 4.229 votos, Paulo Roberto acumula quase 40 anos de experiência parlamentar, tendo sido presidente do Legislativo entre 1983 e 1984.',null,null,'paulo.roberto@camaraguarulhos.sp.gov.br');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Sergio Magnum','PATRIOTA','Sergio Augusto da Silva, o Sergio Magnum (22.8.1967), foi eleito vereador pela primeira vez pelo PEN, com 2.747 votos - em 2018, o partido mudou sua denominação para "PATRIOTA". É filiado ao partido há um ano, depois de passar pelo PSDB. Iniciou na política em 2000, quando se filiou ao PTdoB e tentou uma cadeira no Legislativo guarulhense. Comerciante, é proprietário de uma farmácia no Jardim Lenise. Natural de Franca (SP), é casado e não tem filhos. Ligado às comunidades do Jardim Lenise, São João, Cidade Soberana e Santos Dumont, Sergio Magnum foca sua trabalho na área da Saúde, mas pretende atuar em todas as frentes: “Vivemos uma fase política e economicamente difícil em Guarulhos, como em todo o Brasil, com muita corrupção, e temos que no esforçar para melhorar os índices em todas as áreas áreas, tentando recuperar Guarulhos, uma vez que esta cidade tem sido bem castigada nas últimas gestões”, declarou o vereador eleito.',null,null,'sergio.magnum@camaraguarulhos.sp.gov.br');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Eduardo Carneiro','PSB','Eduardo Carneiro foi eleito para seu segundo mandato com 2.407 votos. Foi vereador pela primeira vez em 2009. Exerce atualmente as funções de líder do Governo na Câmara e de 1º vice-presidente da Mesa Diretora.Natural de Campo Belo (MG), mudou-se para Guarulhos há aproximadamente 30 anos. É casado e tem dois filhos: uma dermatologista e um cardiologista. Mora no Jardim Maia',null,null,'dr.eduardocarneiro@camaraguarulhos.sp.gov.br');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Luis da Sede ','PRTB','Eleito com 2.718 votos, Luis Nunes (59) nasceu em Perero (CE) e veio para Guarulhos há 26 anos. É casado e tem dois filhos. Filiou-se ao PRTB faz um ano. Candidatou-se duas vezes pelo Partido Socialista Brasileiro (PSB), no qual permaneceu por 12 anos. Na primeira candidatura foi derrotado com 1.600 votos e na segunda, com 2.138. No último pleito ficou como terceiro suplente pelo PSB.',null,null,'luis.dasede@camaraguarulhos.sp.gov.br');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Carol Ribeiro','MDB','Carol Ribeiro Freitas, 29 anos (2.7.1987) é natural de Cabo Frio (RJ).  Bacharel em Direito, foi eleita vereadora pelo PMDB com 2.265 votos. Ela é filiada ao partido desde março de 2016. Nas eleições de 2012, Carol Ribeiro ficou como 5ª suplente, então pelo PSDB, tendo assumido por 15 dias a cadeira de vereadora em 2013. Na condição de parlamentar, pretende exercer o mandato dando atenção à população de forma geral, com um olhar especial para o público feminino',null,null,'carolribeiro@camaraguarulhos.sp.gov.br');
INSERT INTO politico (nome,partido,descricao,dtnascimento,email,perfilfacebook) VALUES('Rafa Zampronio','PSB','Rafa Zampronio (PSB) é natural de Guarulhos, onde nasceu em 2 de outubro de 1989. Esta foi sua segunda eleição e a primeira eleito, com 4.176 votos. Filiou-se ao partido em 2015, depois de ter passado por PV e PHS. É escritor e empresário do ramo de engenharia de segurança contra incêndio. Sua proposta de trabalho no Legislativo destaca atenção à Saúde e, principalmente, à Educação. Neste caso, Zampronio propõe para melhorar o ensino um plano de carreira para professores e melhores condições de ensino nas escolas. Segundo ele, esses pilares ajudariam a tornar Guarulhos uma cidade melhor para se viver',null,null,'rafa.zampronio@camaraguarulhos.sp.gov.br');

#Arrumar Campos Com erro nas datas#

SELECT * FROM politico;
SELECT * FROM politico 
	WHERE partido = "PT";